Repository WildCodeSchool/orleans-202103-php-project-treebz, pull requests merged in 2021-06, with the labels that each got.

#20 S01 us03 footer
  assets/images/treebz.png
  assets/styles/app.scss
  assets/styles/footer.scss
  assets/styles/variables.scss
  templates/base.html.twig
  templates/includes/_footer.html.twig
  templates/layout.html.twig
  webpack.config.js
Labels: Reviewed

#26 Dev to master
  assets/app.js
  assets/images/treebz.png
  assets/styles/app.scss
  assets/styles/footer.scss
  assets/styles/variables.scss
  package.json
  templates/base.html.twig
  templates/home/index.html.twig
  templates/includes/_footer.html.twig
  templates/layout.html.twig
  templates/layout_admin.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed

#17 S01US06-01
  assets/images/waves.svg
  assets/styles/app.scss
  assets/styles/home/home.scss
  assets/styles/variables.scss
  package.json
  templates/home/index.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed, conflicts resolved

#42 Dev to Master dans le bon sens :')
  assets/images/waves.svg
  assets/styles/app.scss
  assets/styles/home/home.scss
  assets/styles/variables.scss
  package.json
  templates/home/index.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed

#43 fix affichage lien footer
  assets/styles/app.scss
  assets/styles/footer.scss
Labels: Reviewed

#46 accueil_creer le jeu
  assets/images/cards.svg
  assets/styles/footer.scss
  assets/styles/home/home.scss
  templates/home/index.html.twig
Labels: Reviewed

#28 Us2 navbar boostrap (html+css)
  assets/images/iconeJeuxCartes.png
  assets/images/logoTreebz.webp
  assets/styles/app.scss
  assets/styles/function.scss
  assets/styles/navbar.scss
  composer.json
  composer.lock
  package-lock.json
  templates/base.html.twig
  templates/component/_navbar.html.twig
  templates/layout.html.twig
Labels: Reviewed

#45 add commitments
  assets/images/french-flag.svg
  assets/images/recycling-symbol.svg
  assets/images/tree.svg
  assets/styles/home/home.scss
  templates/home/index.html.twig
Labels: Reviewed, conflicts resolved

#50 S02 us06 03 accueil règles
  assets/styles/home/home.scss
  templates/home/index.html.twig
Labels: Reviewed, conflicts resolved

#47 S02 us01 page accueil admin
  assets/app.js
  assets/styles/admin/homeAdmin.scss
  assets/styles/app.scss
  assets/styles/footer.scss
  package.json
  src/Controller/admin/HomeAdminController.php
  templates/admin/index.html.twig
  templates/layout_admin.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed

#22 US05_Game rules_page complete
  assets/styles/app.scss
  assets/styles/footer.scss
  assets/styles/gamerule.scss
  assets/styles/home/home.scss
  assets/styles/variables.scss
  src/Controller/RuleController.php
  templates/gamerule/index.html.twig
  webpack.config.js
Labels: Reviewed, conflicts resolved

#55 modification logo en transparence
  assets/images/logoTreebz.webp
  assets/styles/home/home.scss
  templates/includes/_footer.html.twig
Labels: Reviewed

#54 Fix home
  assets/styles/app.scss
  assets/styles/home/home.scss
  templates/component/_navbar.html.twig
  templates/component/_navbar_admin.html.twig
  templates/home/index.html.twig
Labels: Reviewed, conflicts resolved

#52 Dev to Master
  assets/app.js
  assets/images/cards.svg
  assets/images/french-flag.svg
  assets/images/iconeJeuxCartes.png
  assets/images/logoTreebz.webp
  assets/images/recycling-symbol.svg
  assets/images/tree.svg
  assets/styles/admin/homeAdmin.scss
  assets/styles/app.scss
  assets/styles/footer.scss
  assets/styles/function.scss
  assets/styles/gamerule.scss
  assets/styles/home/home.scss
  assets/styles/navbar.scss
  assets/styles/variables.scss
  composer.json
  composer.lock
  package-lock.json
  package.json
  src/Controller/RuleController.php
  src/Controller/admin/HomeAdminController.php
  templates/admin/index.html.twig
  templates/base.html.twig
  templates/component/_navbar.html.twig
  templates/component/_navbar_admin.html.twig
  templates/gamerule/index.html.twig
  templates/home/index.html.twig
  templates/includes/_footer.html.twig
  templates/layout.html.twig
  templates/layout_admin.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed

#61 Arrangement home
  assets/images/cards.svg
  assets/styles/admin/homeAdmin.scss
  assets/styles/home/home.scss
Labels: Reviewed

#60 icones accueil
  assets/images/french-flag.svg
  assets/images/french-flag.webp
  assets/images/logoTreebz.webp
  assets/images/recycling-symbol.svg
  assets/images/recycling-symbol.webp
  assets/images/tree.svg
  assets/images/tree.webp
  assets/images/treebz.png
  assets/styles/home/home.scss
  templates/home/index.html.twig
Labels: Reviewed

#63 Fix footer
  assets/styles/footer.scss
  templates/includes/_footer.html.twig
Labels: Reviewed

#64 delete font-fluid
  assets/styles/navbar.scss
Labels: Reviewed

#51 S02 us03 page creation de theme
  assets/styles/admin/newTheme.scss
  assets/styles/app.scss
  config/packages/translation.yaml
  migrations/Version20210609091706.php
  src/Controller/ThemeController.php
  src/Entity/Theme.php
  src/Form/ThemeType.php
  src/Repository/ThemeRepository.php
  templates/admin/theme/_delete_form.html.twig
  templates/admin/theme/_form.html.twig
  templates/admin/theme/edit.html.twig
  templates/admin/theme/index.html.twig
  templates/admin/theme/new.html.twig
  templates/admin/theme/show.html.twig
  webpack.config.js
Labels: Reviewed

#65 Changement règles accueil
  assets/images/orangecards.svg
  assets/styles/home/home.scss
  templates/home/index.html.twig
Labels: Reviewed

#66 make footer appear
  templates/gamerule/index.html.twig
Labels: Reviewed

#68 link home navbar
  templates/component/_navbar.html.twig
  templates/component/_navbar_admin.html.twig
Labels: Reviewed

#67 Dev to Master
  assets/images/cards.svg
  assets/images/french-flag.svg
  assets/images/french-flag.webp
  assets/images/logoTreebz.webp
  assets/images/orangecards.svg
  assets/images/recycling-symbol.svg
  assets/images/recycling-symbol.webp
  assets/images/tree.svg
  assets/images/tree.webp
  assets/images/treebz.png
  assets/styles/admin/homeAdmin.scss
  assets/styles/admin/newTheme.scss
  assets/styles/app.scss
  assets/styles/footer.scss
  assets/styles/home/home.scss
  assets/styles/navbar.scss
  config/packages/translation.yaml
  migrations/Version20210609091706.php
  src/Controller/ThemeController.php
  src/Entity/Theme.php
  src/Form/ThemeType.php
  src/Repository/ThemeRepository.php
  templates/admin/theme/_delete_form.html.twig
  templates/admin/theme/_form.html.twig
  templates/admin/theme/edit.html.twig
  templates/admin/theme/index.html.twig
  templates/admin/theme/new.html.twig
  templates/admin/theme/show.html.twig
  templates/component/_navbar.html.twig
  templates/component/_navbar_admin.html.twig
  templates/gamerule/index.html.twig
  templates/home/index.html.twig
  templates/includes/_footer.html.twig
  webpack.config.js
Labels: Reviewed

#62 US04_1de4_Creer Jeu
  .gitignore
  assets/images/arrow-right.svg
  assets/images/step_gamecreation.svg
  assets/styles/gamecreation.scss
  migrations/Version20210609091706.php
  migrations/Version20210611085720.php
  src/Controller/GameCreationController.php
  src/Entity/Command.php
  src/Form/CommandType.php
  src/Repository/CommandRepository.php
  templates/gameCreation/index.html.twig
  webpack.config.js
Labels: Reviewed

#92 Fix migration
  migrations/Version20210611091617.php
Labels: Reviewed

#93 FIX - form property name
  templates/gameCreation/index.html.twig
Labels: Reviewed

#95 US05 - Validation and submition of the $projectName to database
  assets/styles/gamecreation.scss
  src/Controller/GameCreationController.php
  src/Entity/Command.php
  templates/gameCreation/index.html.twig
Labels: Reviewed

#100 contact creation with controller
  assets/images/envelope.svg
  assets/styles/contact/contact.scss
  config/packages/translation.yaml
  config/services.yaml
  src/Controller/ContactController.php
  src/Entity/Contact.php
  src/Form/ContactType.php
  src/Repository/ContactRepository.php
  templates/component/_navbar.html.twig
  templates/contact/contact.html.twig
  templates/contact/newContactEmail.html.twig
  templates/layoutEmail.html.twig
  webpack.config.js
Labels: Correction done, Reviewed

#118 US10_CreerJeu Page3 ind
  assets/styles/gamecreation.scss
  assets/styles/variables.scss
  migrations/Version20210611091617.php
  src/Controller/GameCreationController.php
  templates/gameCreation/index.html.twig
  templates/gameCreation/theme.html.twig
Labels: Reviewed

#104 fix_upload_theme
  composer.json
  composer.lock
  config/bundles.php
  config/packages/vich_uploader.yaml
  config/services.yaml
  migrations/Version20210616142848.php
  public/uploads/V2 noir.svg
  public/uploads/medaille-argent.png
  src/Entity/Theme.php
  src/Form/ThemeType.php
  symfony.lock
  templates/admin/theme/index.html.twig
  templates/admin/theme/new.html.twig
Labels: Reviewed

#120 Création connexion utilisateur
  assets/styles/connexion/connexion.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/reset_password.yaml
  config/packages/security.yaml
  migrations/Version20210617091522.php
  src/Controller/SecurityController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Repository/UserRepository.php
  src/Security/LoginFormAuthenticator.php
  symfony.lock
  templates/component/_navbar.html.twig
  templates/security/login.html.twig
  webpack.config.js
Labels: Reviewed, conflicts resolved

#123 upload fix and name to upper in member
  src/Controller/MemberController.php
  src/Entity/Member.php
Labels: Reviewed

#121 S03 us01 lister les theme
  assets/styles/admin/indexTheme.scss
  src/Controller/ThemeController.php
  src/Entity/Theme.php
  templates/admin/theme/_delete_form.html.twig
  templates/admin/theme/edit.html.twig
  templates/admin/theme/index.html.twig
  templates/admin/theme/show.html.twig
  webpack.config.js
Labels: Reviewed

#130 S03 us08 edit theme
  src/Form/ThemeType.php
  templates/admin/theme/_form.html.twig
  templates/admin/theme/edit.html.twig
Labels: Reviewed, conflicts resolved

#133 Us7 fixture member
  assets/images/Annick part en voyage.webp
  assets/images/portrait.jpg
  assets/styles/app.scss
  assets/styles/gamecreation.scss
  composer.json
  composer.lock
  config/packages/vich_uploader.yaml
  public/uploads/V2 noir.svg
  public/uploads/medaille-argent.png
  public/uploads_member/IMG_20200715_175801.jpg
  public/uploads_member/IMG_20200720_160121.jpg
  src/Controller/MemberController.php
  src/DataFixtures/MemberFixtures.php
  src/Entity/Member.php
  symfony.lock
  templates/member/_delete_form.html.twig
  templates/member/index.html.twig
  templates/member/new.html.twig
Labels: Reviewed

#134 flash_contact
  src/Controller/ContactController.php
  templates/base.html.twig
Labels: Reviewed

#139 Fix - StepBar - Colors and its progress
  templates/gameCreation/index.html.twig
  templates/gameCreation/theme.html.twig
  templates/member/index.html.twig
Labels: Reviewed

#137 US17 - Fixtures for Theme and Command
  composer.json
  composer.lock
  image.jpg
  src/DataFixtures/ProjectFixtures.php
  src/DataFixtures/ThemeFixtures.php
  src/Entity/Theme.php
  symfony.lock
  webpack.config.js
Labels: Reviewed

#140 Fix généraux 2
  assets/styles/contact/contact.scss
  templates/contact/contact.html.twig
  templates/gamerule/index.html.twig
Labels: Reviewed

#142 Fix_Design_Game Creation and Buttons
  assets/images/cards.png
  assets/images/cards.svg
  assets/styles/app.scss
  assets/styles/footer.scss
  assets/styles/gamecreation.scss
  public/uploads/.gitignore
  templates/gameCreation/index.html.twig
  templates/gameCreation/theme.html.twig
  templates/home/index.html.twig
  templates/includes/_footer.html.twig
  templates/member/index.html.twig
  templates/member/new.html.twig
Labels: Reviewed

#148 Correction lien connexion navbar
  templates/component/_navbar.html.twig
Labels: Reviewed

#143 Fix in the path for Theme image exhibit
  assets/styles/gamecreation.scss
  public/uploads/.gitignore
  src/DataFixtures/ThemeFixtures.php
  templates/gameCreation/theme.html.twig
Labels: Reviewed, conflicts resolved

#145 lien entre les page de création de jeu
  assets/images/membre_mamie.webp
  migrations/Version20210622145520.php
  src/Controller/GameCreationController.php
  src/Controller/MemberController.php
  src/DataFixtures/MemberFixtures.php
  src/Entity/Command.php
  src/Entity/Member.php
  templates/component/_navbar.html.twig
  templates/gameCreation/index.html.twig
  templates/gameCreation/theme.html.twig
  templates/home/index.html.twig
  templates/member/_delete_form.html.twig
  templates/member/edit.html.twig
  templates/member/index.html.twig
  templates/member/new.html.twig
Labels: Reviewed

#146 S04US13_creation_compte
  assets/styles/connexion/connexion.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/twig.yaml
  migrations/Version20210624142026.php
  src/Controller/RegistrationController.php
  src/Entity/User.php
  src/Entity/UserDetail.php
  src/Form/RegistrationFormType.php
  src/Form/UserDetailType.php
  src/Repository/UserDetailRepository.php
  src/Security/EmailVerifier.php
  symfony.lock
  templates/registration/confirmation_email.html.twig
  templates/registration/register.html.twig
Labels: Reviewed

#151 S04US12 Securisation des routes admin
  config/packages/security.yaml
  templates/component/_navbar.html.twig
  templates/component/_navbar_admin.html.twig
Labels: Reviewed

#160 Us19 - Politique de Confidentialité
  src/Controller/TermController.php
  templates/terms/policy.html.twig
Labels: Reviewed

#157 card's name, id and pictures view
  assets/images/Annick part en voyage.webp
  assets/styles/app.scss
  assets/styles/card/card.scss
  src/Controller/CardController.php
  templates/card.html.twig
  webpack.config.js
Labels: Reviewed

#159 Dev to master
  assets/images/Annick part en voyage.webp
  assets/images/cards.png
  assets/images/cards.svg
  assets/images/membre_mamie.webp
  assets/styles/app.scss
  assets/styles/card/card.scss
  assets/styles/connexion/connexion.scss
  assets/styles/contact/contact.scss
  assets/styles/footer.scss
  assets/styles/gamecreation.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/security.yaml
  config/packages/twig.yaml
  image.jpg
  migrations/Version20210622145520.php
  migrations/Version20210624142026.php
  public/uploads/.gitignore
  src/Controller/Admin/HomeAdminController.php
  src/Controller/Admin/ThemeController.php
  src/Controller/CardController.php
  src/Controller/GameCreationController.php
  src/Controller/MemberController.php
  src/Controller/RegistrationController.php
  src/Controller/TermController.php
  src/DataFixtures/MemberFixtures.php
  src/DataFixtures/ProjectFixtures.php
  src/DataFixtures/ThemeFixtures.php
  src/Entity/Command.php
  src/Entity/Member.php
  src/Entity/Theme.php
  src/Entity/User.php
  src/Entity/UserDetail.php
  src/Form/RegistrationFormType.php
  src/Form/UserDetailType.php
  src/Repository/UserDetailRepository.php
  src/Security/EmailVerifier.php
  symfony.lock
  templates/admin/index.html.twig
  templates/card.html.twig
  templates/component/_navbar.html.twig
  templates/component/_navbar_admin.html.twig
  templates/contact/contact.html.twig
  templates/gameCreation/index.html.twig
  templates/gameCreation/theme.html.twig
  templates/gamerule/index.html.twig
  templates/home/index.html.twig
  templates/includes/_footer.html.twig
  templates/member/_delete_form.html.twig
  templates/member/edit.html.twig
  templates/member/index.html.twig
  templates/member/new.html.twig
  templates/registration/confirmation_email.html.twig
  templates/registration/register.html.twig
  templates/terms/policy.html.twig
  webpack.config.js
Labels: Reviewed

#168 S04 US20 page condition generale
  src/Controller/TermController.php
  templates/includes/_footer.html.twig
  templates/terms/termOfService.html.twig
Labels: Reviewed

#170 Correction fix_style_lien
  templates/component/_navbar.html.twig
  templates/layout.html.twig
  templates/security/login.html.twig
  templates/terms/termOfService.html.twig
Labels: Reviewed

#172 modiffication de l'apparence de edit member
  src/Controller/MemberController.php
  templates/member/_delete_form.html.twig
  templates/member/edit.html.twig
Labels: Reviewed

#171 Dev to master
  src/Controller/MemberController.php
  src/Controller/TermController.php
  templates/component/_navbar.html.twig
  templates/includes/_footer.html.twig
  templates/layout.html.twig
  templates/member/_delete_form.html.twig
  templates/member/edit.html.twig
  templates/security/login.html.twig
  templates/terms/termOfService.html.twig
Labels: Reviewed

#195 fix view picture
  templates/member/index.html.twig
Labels: Reviewed
