Repository WildCodeSchool/orleans-202103-php-project-treebz, pull requests merged in 2021-07, with the labels that each got.

#197 Fix Route Protection de donnes
  composer.json
  composer.lock
  src/Controller/TermController.php
Labels: Reviewed

#203 prévisualisation des cartes pour pdf
  assets/styles/card/card.scss
  public/uploads/.gitignore
  src/Controller/CardController.php
  src/DataFixtures/MemberFixtures.php
  templates/card.html.twig
Labels: Reviewed

#158 S04 us16 mdp oublier
  .env
  composer.json
  composer.lock
  config/packages/reset_password.yaml
  config/packages/twig.yaml
  migrations/Version20210624083810.php
  phpstan.neon
  src/Controller/security/ResetPasswordController.php
  src/Controller/security/SecurityController.php
  src/Entity/ResetPasswordRequest.php
  src/Form/ChangePasswordFormType.php
  src/Form/ResetPasswordRequestFormType.php
  src/Repository/ResetPasswordRequestRepository.php
  templates/layout.html.twig
  templates/security/login.html.twig
  templates/security/reset_password/check_email.html.twig
  templates/security/reset_password/email.html.twig
  templates/security/reset_password/request.html.twig
  templates/security/reset_password/reset.html.twig
Labels: Reviewed

#204 Us19 User Account section
  src/Controller/UserDetailController.php
  templates/component/_navbar.html.twig
  templates/user_detail/_form.html.twig
  templates/user_detail/edit.html.twig
Labels: Reviewed

#217 Fix footer
  assets/styles/app.scss
  templates/includes/_footer.html.twig
Labels: Reviewed

#208 S05 us24 affichage des commandes
  assets/styles/admin/command.scss
  migrations/Version20210701143820.php
  migrations/Version20210704134710.php
  src/Controller/Admin/CommandController.php
  src/DataFixtures/CommandFixtures.php
  src/DataFixtures/MemberFixtures.php
  src/DataFixtures/ProjectFixtures.php
  src/DataFixtures/StatusFixtures.php
  src/DataFixtures/ThemeFixtures.php
  src/DataFixtures/UserDetailFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Command.php
  src/Entity/Status.php
  src/Entity/User.php
  src/Entity/UserDetail.php
  src/Repository/StatusRepository.php
  templates/admin/command/index.html.twig
  templates/component/_magnifying_glass.html.twig
  templates/component/_navbar_admin.html.twig
  webpack.config.js
Labels: Reviewed

#220 Dev to master
  .env
  assets/styles/admin/command.scss
  assets/styles/app.scss
  assets/styles/card/card.scss
  composer.json
  composer.lock
  config/packages/reset_password.yaml
  config/packages/twig.yaml
  migrations/Version20210624083810.php
  migrations/Version20210701143820.php
  migrations/Version20210704134710.php
  phpstan.neon
  public/uploads/.gitignore
  src/Controller/Admin/CommandController.php
  src/Controller/CardController.php
  src/Controller/TermController.php
  src/Controller/UserDetailController.php
  src/Controller/security/ResetPasswordController.php
  src/Controller/security/SecurityController.php
  src/DataFixtures/CommandFixtures.php
  src/DataFixtures/MemberFixtures.php
  src/DataFixtures/ProjectFixtures.php
  src/DataFixtures/StatusFixtures.php
  src/DataFixtures/ThemeFixtures.php
  src/DataFixtures/UserDetailFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Command.php
  src/Entity/ResetPasswordRequest.php
  src/Entity/Status.php
  src/Entity/User.php
  src/Entity/UserDetail.php
  src/Form/ChangePasswordFormType.php
  src/Form/ResetPasswordRequestFormType.php
  src/Repository/ResetPasswordRequestRepository.php
  src/Repository/StatusRepository.php
  templates/admin/command/index.html.twig
  templates/card.html.twig
  templates/component/_magnifying_glass.html.twig
  templates/component/_navbar.html.twig
  templates/component/_navbar_admin.html.twig
  templates/includes/_footer.html.twig
  templates/layout.html.twig
  templates/member/index.html.twig
  templates/security/login.html.twig
  templates/security/reset_password/check_email.html.twig
  templates/security/reset_password/email.html.twig
  templates/security/reset_password/request.html.twig
  templates/security/reset_password/reset.html.twig
  templates/user_detail/_form.html.twig
  templates/user_detail/edit.html.twig
  webpack.config.js
Labels: Reviewed

#218 US26 - User managemenet for the admin part
  src/Controller/AdminUserController.php
  src/Form/UserDetailType.php
  src/Repository/UserDetailRepository.php
  templates/admin/user/_delete_form.html.twig
  templates/admin/user/_form.html.twig
  templates/admin/user/edit.html.twig
  templates/admin/user/index.html.twig
  templates/component/_navbar_admin.html.twig
Labels: Correction done, Reviewed

#221 Fix on the connexion page, fix in the admin navbar, fix in the conditions for the greetings (name or email if there's isnt a name)
  src/Controller/TermController.php
  templates/component/_navbar.html.twig
  templates/component/_navbar_admin.html.twig
  templates/includes/_footer.html.twig
  templates/layout.html.twig
  templates/security/login.html.twig
Labels: Correction done, Reviewed

#207 Fix link command member theme link fixtures
  composer.lock
  migrations/Version20210706052820.php
  src/DataFixtures/CommandFixtures.php
  src/DataFixtures/MemberFixtures.php
  src/DataFixtures/ThemeFixtures.php
  src/DataFixtures/canva_png/1.png
  src/DataFixtures/canva_png/2.png
  src/DataFixtures/canva_png/3.png
  webpack.config.js
Labels: Reviewed

#219 creation d'un service pour le prix d un jeu
  src/Controller/MemberController.php
  src/Service/GameCard.php
  templates/gameCreation/index.html.twig
  templates/member/index.html.twig
Labels: Correction done, Reviewed

#230 fix migrations qui fonctionnent
  migrations/.gitignore
  migrations/Version20210706052820.php
  migrations/Version20210706201451.php
Labels: Reviewed

#233 fix image webpack hash
  webpack.config.js
Labels: Reviewed

#236 Dev -> Master
  migrations/.gitignore
  migrations/Version20210706052820.php
  migrations/Version20210706201451.php
  src/Controller/MemberController.php
  src/Service/GameCard.php
  templates/gameCreation/index.html.twig
  templates/member/index.html.twig
  webpack.config.js
Labels: Reviewed

#237 US 32 - Client search by lastname (Admin)
  src/Controller/AdminUserController.php
  src/Entity/SearchClient.php
  src/Form/SearchClientType.php
  src/Repository/UserDetailRepository.php
  templates/admin/user/index.html.twig
Labels: Reviewed

#240 fix
  assets/styles/preview.scss
  src/Controller/RegistrationController.php
  src/Controller/security/ResetPasswordController.php
  src/DataFixtures/MemberFixtures.php
  templates/admin/user/_delete_form.html.twig
  templates/admin/user/index.html.twig
  templates/gameCreation/index.html.twig
  templates/gameCreation/preview.html.twig
  templates/gameCreation/theme.html.twig
  templates/registration/confirmation_email.html.twig
Labels: Reviewed

#238 services prix en fonction des themes
  src/Controller/GameCreationController.php
  src/Service/GameCard.php
  templates/gameCreation/theme.html.twig
Labels: Reviewed, question

#223 cropperJS installation
  assets/controllers.json
  assets/images/La famille Ecolo.png
  assets/styles/gamecreation.scss
  composer.json
  composer.lock
  config/bundles.php
  config/services.yaml
  package.json
  src/Controller/MemberController.php
  symfony.lock
  templates/member/crop.html.twig
  yarn.lock
Labels: Correction done, Reviewed

#252 fix modifier membres
  src/Form/MemberType.php
  templates/member/edit.html.twig
Labels: Reviewed

#253 US 27 | Securisation de la partie de membres et recapitulatif
  src/Controller/MemberController.php
  src/Controller/PreviewController.php
Labels: Reviewed

#256 page remerciements
  src/Controller/ThanksController.php
  templates/gameCreation/preview.html.twig
  templates/gameCreation/thanks.html.twig
Labels: Reviewed

#241 S05 us31 modification des status
  assets/styles/admin/command.scss
  assets/styles/variables.scss
  migrations/Version20210708132044.php
  src/Controller/Admin/CommandController.php
  src/DataFixtures/StatusFixtures.php
  src/Entity/Status.php
  templates/admin/command/index.html.twig
Labels: Correction done, Reviewed

#251 US34: Creation of the page to edit the project name and insertion of buttons to return to the earlier step.
  src/Controller/GameCreationController.php
  src/Form/GameType.php
  templates/component/_left_arrow.html.twig
  templates/gameCreation/editGameName.html.twig
  templates/gameCreation/preview.html.twig
  templates/gameCreation/theme.html.twig
  templates/member/index.html.twig
  templates/member/new.html.twig
Labels: Correction done, Reviewed

#258 fix historique des commandes
  templates/user_detail/commandHistory.html.twig
Labels: Reviewed

#259 crop when modified
  src/Controller/MemberController.php
Labels: Reviewed

#260 fix lien de la page d'accueil admin
  composer.lock
  templates/admin/index.html.twig
Labels: Reviewed

#263 Fix - Inserting links in the box form to accept the terms and conditions of the website
  src/Form/RegistrationFormType.php
  templates/component/_navbar_admin.html.twig
  templates/registration/register.html.twig
Labels: Reviewed

#262 fix style
  assets/styles/gamerule.scss
  templates/gamerule/index.html.twig
  templates/terms/policy.html.twig
  templates/terms/termOfService.html.twig
Labels: Reviewed

#264 fix_research_command
  src/Controller/Admin/CommandController.php
  src/Form/SearchCommandType.php
  src/Repository/CommandRepository.php
Labels: Reviewed

#257 Fix Links in Admin and fix in the style of search field
  src/Controller/AdminUserController.php
  src/Form/SearchClientType.php
  templates/admin/index.html.twig
  templates/admin/user/index.html.twig
  templates/component/_navbar_admin.html.twig
Labels: Reviewed, conflicts resolved

#266 fix statuts a la création commande
  src/Controller/GameCreationController.php
Labels: Reviewed

#279 Us24 admin trier les commandes par statuts
  src/Controller/Admin/CommandController.php
  src/Form/StatusSearchType.php
  templates/admin/command/index.html.twig
Labels: Reviewed

#282 S06 us05 comfirmation mot de passe
  src/Form/RegistrationFormType.php
  templates/registration/register.html.twig
Labels: Reviewed

#286 previsualisation
  assets/images/La famille Ecolo.png
  assets/images/theme_previsualisation.png
  assets/styles/gamecreation.scss
  src/Controller/MemberController.php
  templates/member/crop.html.twig
  templates/member/edit.html.twig
Labels: Reviewed

#284 US02 - Ajouter une adresse de livraison
  migrations/Version20210708132044.php
  migrations/Version20210713072302.php
  src/Controller/PreviewController.php
  src/Entity/Command.php
  src/Entity/ShippingAddress.php
  src/Entity/User.php
  src/Form/SelectAddressType.php
  src/Form/ShippingAddressType.php
  src/Repository/ShippingAddressRepository.php
  templates/gameCreation/preview.html.twig
  templates/shipping_address/_delete_form.html.twig
  templates/shipping_address/_form.html.twig
  templates/shipping_address/edit.html.twig
  templates/shipping_address/index.html.twig
  templates/shipping_address/new.html.twig
  templates/shipping_address/show.html.twig
Labels: Correction done, Reviewed

#280 changement de numeros des cartes
  assets/styles/gamecreation.scss
  migrations/Version20210709205717.php
  package-lock.json
  src/Controller/MemberController.php
  src/DataFixtures/MemberFixtures.php
  src/Entity/Member.php
  templates/member/index.html.twig
Labels: Reviewed, conflicts resolved

#281 S05 us33 récuperer sa dernière creation
  src/Controller/GameCreationController.php
  src/Controller/UserDetailController.php
  templates/component/_navbar.html.twig
  templates/gameCreation/index.html.twig
  templates/user_detail/commandHistory.html.twig
Labels: Reviewed

#290 ajout de theme en fixtures
  src/DataFixtures/ThemeFixtures.php
  src/DataFixtures/canva_png/2.png
  src/DataFixtures/canva_png/3.png
  src/DataFixtures/canva_png/4.png
  src/DataFixtures/canva_png/5.png
  src/DataFixtures/canva_png/6.png
  src/DataFixtures/canva_png/7.png
  src/DataFixtures/canva_png/8.png
  src/DataFixtures/canva_png/9.png
Labels: Reviewed

#289 S06 us01 01 convert to pdf
  assets/images/DosDeCarte.png
  assets/styles/pdf.scss
  composer.json
  composer.lock
  src/Controller/PdfController.php
  symfony.lock
  templates/admin/command/index.html.twig
  templates/back_pdf.html.twig
  templates/card.html.twig
  templates/component/_one_card_preview.html.twig
  templates/pdf.html.twig
  webpack.config.js
Labels: Reviewed, conflicts resolved

#291 Fix theme membre avant previsualisation
  templates/gameCreation/theme.html.twig
  templates/member/index.html.twig
Labels: Reviewed

#287 View recapitulatif commande
  assets/styles/app.scss
  assets/styles/preview.scss
  src/Controller/PreviewController.php
  templates/gameCreation/preview.html.twig
Labels: Reviewed

#292 fix_color
  templates/component/_card_preview.html.twig
  templates/component/_one_card_preview.html.twig
Labels: Reviewed

#296 Updating readme after real tests.
  README.md
Labels: Reviewed

#297 Pages d'erreur
  templates/bundles/TwigBundle/Exception/error.html.twig
  templates/bundles/TwigBundle/Exception/error401.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/bundles/TwigBundle/Exception/error500.html.twig
Labels: Reviewed

#293 Fix Style Sections - GameCreation (member - theme)
  assets/styles/gamecreation.scss
  templates/gameCreation/theme.html.twig
  templates/member/index.html.twig
Labels: Reviewed

#311 fix_sécurisation_route_inscription
  src/Controller/RegistrationController.php
Labels: Reviewed

#312 fix_CGU_footer
  templates/includes/_footer.html.twig
Labels: Reviewed

#314 fix dos de carte
  assets/styles/pdf.scss
  migrations/Version20210715080033.php
  src/Entity/Command.php
  src/Entity/Member.php
  templates/back_pdf.html.twig
Labels: Reviewed

#315 Fix in the contact page, so the connected user does not need to insert data already available in our db.
  templates/contact/contact.html.twig
Labels: Reviewed

#318 fix_suppression_user
  migrations/Version20210715091620.php
  src/Entity/Command.php
Labels: Reviewed

#316 Add Btn JS Print
  assets/styles/pdf.scss
  templates/back_pdf.html.twig
  templates/pdf.html.twig
Labels: Reviewed

#313 changement d'algo pour les fleche dans twig
  templates/member/index.html.twig
Labels: Reviewed

#319 Fix favicon
  assets/images/treebz.png
Labels: Reviewed

#320 Tuto Crop
  assets/images/portrait.jpg
  templates/member/crop.html.twig
Labels: Reviewed

#321 fix ortho
  src/Form/SelectAddressType.php
Labels: Reviewed

#322 fix_couleur_themes
  assets/styles/admin/indexTheme.scss
  templates/admin/theme/index.html.twig
Labels: Reviewed

#317 Update ReadMe
  README.md
Labels: Reviewed

#323 theme => famille
  src/Controller/Admin/ThemeController.php
  src/Controller/GameCreationController.php
  src/Form/ThemeType.php
  templates/admin/index.html.twig
  templates/admin/theme/edit.html.twig
  templates/admin/theme/index.html.twig
  templates/admin/theme/new.html.twig
  templates/component/_navbar_admin.html.twig
  templates/gameCreation/editGameName.html.twig
  templates/gameCreation/index.html.twig
  templates/gameCreation/preview.html.twig
  templates/gameCreation/theme.html.twig
  templates/home/index.html.twig
  templates/member/crop.html.twig
  templates/member/edit.html.twig
  templates/member/index.html.twig
  templates/member/new.html.twig
Labels: Reviewed

#324 reorganisation des numéros de carte lors d'une suppression
  src/Controller/MemberController.php
Labels: Reviewed

#327 fatal error corrected
  templates/component/_navbar.html.twig
Labels: Reviewed

#325 cleaning scss files
  assets/styles/app.scss
  assets/styles/card/card.scss
  assets/styles/connexion/connexion.scss
  assets/styles/gamerule.scss
  assets/styles/navbar.scss
  assets/styles/pdf.scss
  assets/styles/preview.scss
  assets/styles/variables.scss
  webpack.config.js
Labels: Reviewed

#328 Dev => Master
  README.md
  assets/images/portrait.jpg
  assets/images/treebz.png
  assets/styles/admin/indexTheme.scss
  assets/styles/app.scss
  assets/styles/card/card.scss
  assets/styles/connexion/connexion.scss
  assets/styles/gamecreation.scss
  assets/styles/gamerule.scss
  assets/styles/navbar.scss
  assets/styles/pdf.scss
  assets/styles/preview.scss
  assets/styles/variables.scss
  migrations/Version20210715080033.php
  migrations/Version20210715091620.php
  src/Controller/Admin/ThemeController.php
  src/Controller/GameCreationController.php
  src/Controller/MemberController.php
  src/Controller/RegistrationController.php
  src/Entity/Command.php
  src/Entity/Member.php
  src/Form/SelectAddressType.php
  src/Form/ThemeType.php
  templates/admin/index.html.twig
  templates/admin/theme/edit.html.twig
  templates/admin/theme/index.html.twig
  templates/admin/theme/new.html.twig
  templates/back_pdf.html.twig
  templates/bundles/TwigBundle/Exception/error.html.twig
  templates/bundles/TwigBundle/Exception/error401.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  templates/bundles/TwigBundle/Exception/error500.html.twig
  templates/component/_navbar.html.twig
  templates/component/_navbar_admin.html.twig
  templates/contact/contact.html.twig
  templates/gameCreation/editGameName.html.twig
  templates/gameCreation/index.html.twig
  templates/gameCreation/preview.html.twig
  templates/gameCreation/theme.html.twig
  templates/home/index.html.twig
  templates/includes/_footer.html.twig
  templates/member/crop.html.twig
  templates/member/edit.html.twig
  templates/member/index.html.twig
  templates/member/new.html.twig
  templates/pdf.html.twig
  webpack.config.js
Labels: Reviewed

#326 modification text creation etape 1
  src/Controller/GameCreationController.php
  templates/gameCreation/editGameName.html.twig
  templates/gameCreation/index.html.twig
Labels: Reviewed, conflicts resolved

#330 Fix rapel prix jeux en fonction des membres
  assets/styles/gamecreation.scss
  templates/member/index.html.twig
Labels: Reviewed

#329 fix_hover_navbar
  assets/styles/navbar.scss
  templates/component/_navbar.html.twig
  templates/layout.html.twig
  webpack.config.js
Labels: Reviewed, conflicts resolved

#331 changement statuts de commande apres avoir paye
  src/Controller/ThanksController.php
  templates/gameCreation/preview.html.twig
Labels: Reviewed

#332 fix chargement commande en cours dans la creation de jeu
  assets/images/masque_member.png
  src/Controller/GameCreationController.php
  templates/member/index.html.twig
Labels: Reviewed

#333 Preview back cards
  templates/gameCreation/preview.html.twig
Labels: Reviewed

#335 fix uploads
  assets/styles/gamecreation.scss
Labels: Reviewed

#334 Dev => Master
  assets/images/masque_member.png
  assets/styles/gamecreation.scss
  assets/styles/navbar.scss
  src/Controller/GameCreationController.php
  src/Controller/MemberController.php
  src/Controller/ThanksController.php
  src/Entity/Member.php
  templates/component/_navbar.html.twig
  templates/gameCreation/editGameName.html.twig
  templates/gameCreation/index.html.twig
  templates/gameCreation/preview.html.twig
  templates/layout.html.twig
  templates/member/index.html.twig
  webpack.config.js
Labels: Reviewed

#337 fix index affichage photo
  templates/member/index.html.twig
Labels: Reviewed

#338 changement de bouton et icon et integration d un fragment
  src/Controller/MemberController.php
  templates/member/index.html.twig
Labels: Reviewed

#339 Preview back card
  assets/styles/app.scss
  assets/styles/pdf.scss
  templates/gameCreation/preview.html.twig
  templates/member/index.html.twig
Labels: Reviewed

#340 Resize img
  src/Controller/MemberController.php
  src/Entity/Theme.php
Labels: Reviewed

#341 chargement d une photo pour les fixtures des membres beaucoup beaucou…
  src/DataFixtures/MemberFixtures.php
Labels: Reviewed

#344 fix home
  assets/images/waves.svg
Labels: Reviewed

#347 Fix bouton retour à l'étape précédente
  templates/member/edit.html.twig
Labels: Reviewed

#348 chargement de la vue en fonction du statuts
  src/Controller/Admin/CommandController.php
  src/Form/StatusSearchType.php
Labels: Reviewed

#346 fix label commande
  templates/admin/command/index.html.twig
Labels: Reviewed

#342 Fix - Changing style from theme selection page (Gamecreation)
  assets/images/check.svg
  assets/styles/gamecreation.scss
  src/Controller/GameCreationController.php
  src/Form/SelectThemesType.php
  templates/component/check.html.twig
  templates/gameCreation/theme.html.twig
Labels: Reviewed, conflicts resolved

#352 retirer l'email si admin car trop long
  templates/component/_navbar.html.twig
Labels: Reviewed

#353 Fix_Upload_Style
  src/Form/ThemeType.php
  templates/admin/theme/new.html.twig
  templates/member/new.html.twig
Labels: Reviewed

#355 fix message flash et non possibilite de passer a l etape suivante si …
  src/Controller/GameCreationController.php
Labels: Reviewed

#354 Fix familly selection
  assets/styles/gamecreation.scss
Labels: Reviewed

#349 Fix - Admin Clients - Accordion and buttons delete/edit
  templates/admin/user/_delete_form.html.twig
  templates/admin/user/edit.html.twig
  templates/admin/user/index.html.twig
Labels: Reviewed

#356 Fix | Preview Page: Fix in the post button (to require the address choise) and style optimization
  src/Controller/PreviewController.php
  src/Form/SelectAddressType.php
  src/Form/ShippingAddressType.php
  templates/gameCreation/preview.html.twig
Labels: Reviewed

#351 Dev ==> Master
  assets/images/check.svg
  assets/images/waves.svg
  assets/styles/app.scss
  assets/styles/gamecreation.scss
  assets/styles/pdf.scss
  src/Controller/Admin/CommandController.php
  src/Controller/GameCreationController.php
  src/Controller/MemberController.php
  src/Controller/PreviewController.php
  src/DataFixtures/MemberFixtures.php
  src/DataFixtures/ThemeFixtures.php
  src/DataFixtures/canva_png/1.png
  src/DataFixtures/canva_png/2.png
  src/DataFixtures/canva_png/3.png
  src/DataFixtures/canva_png/4.png
  src/DataFixtures/canva_png/5.png
  src/DataFixtures/canva_png/6.png
  src/DataFixtures/canva_png/7.png
  src/DataFixtures/canva_png/8.png
  src/DataFixtures/canva_png/9.png
  src/DataFixtures/canva_png/FamilleAventure.png
  src/DataFixtures/canva_png/FamilleCuisine.png
  src/DataFixtures/canva_png/FamilleEcolo.png
  src/DataFixtures/canva_png/FamilleFete.png
  src/DataFixtures/canva_png/FamillePaysan.png
  src/DataFixtures/canva_png/FamilleSki.png
  src/DataFixtures/canva_png/FamilleSport.png
  src/DataFixtures/canva_png/FamilleVoyage.png
  src/Entity/Theme.php
  src/Form/SelectAddressType.php
  src/Form/SelectThemesType.php
  src/Form/ShippingAddressType.php
  src/Form/StatusSearchType.php
  src/Form/ThemeType.php
  templates/admin/command/index.html.twig
  templates/admin/theme/new.html.twig
  templates/admin/user/_delete_form.html.twig
  templates/admin/user/edit.html.twig
  templates/admin/user/index.html.twig
  templates/component/_navbar.html.twig
  templates/component/check.html.twig
  templates/gameCreation/preview.html.twig
  templates/gameCreation/theme.html.twig
  templates/member/edit.html.twig
  templates/member/index.html.twig
  templates/member/new.html.twig
Labels: Reviewed

#357 Fix_Orthographe
  templates/component/_navbar.html.twig
  templates/gameCreation/index.html.twig
  templates/gameCreation/preview.html.twig
  templates/gameCreation/thanks.html.twig
  templates/gameCreation/theme.html.twig
  templates/home/index.html.twig
  templates/member/_form.html.twig
  templates/member/crop.html.twig
  templates/member/edit.html.twig
  templates/member/index.html.twig
  templates/member/new.html.twig
  templates/security/reset_password/request.html.twig
  templates/security/reset_password/reset.html.twig
  templates/user_detail/commandHistory.html.twig
Labels: Reviewed

#358 fix style commande admin
  assets/styles/admin/command.scss
  templates/admin/command/index.html.twig
Labels: Reviewed

#359 migration insert status
  migrations/Version20210715091620.php
Labels: Reviewed

#360 Fix buttons page crop
  templates/member/crop.html.twig
Labels: Correction done, Reviewed

#361 Dev ==> Master
  assets/styles/admin/command.scss
  migrations/Version20210715091620.php
  templates/admin/command/index.html.twig
  templates/component/_navbar.html.twig
  templates/gameCreation/index.html.twig
  templates/gameCreation/preview.html.twig
  templates/gameCreation/thanks.html.twig
  templates/gameCreation/theme.html.twig
  templates/home/index.html.twig
  templates/member/_form.html.twig
  templates/member/crop.html.twig
  templates/member/edit.html.twig
  templates/member/index.html.twig
  templates/member/new.html.twig
  templates/security/reset_password/request.html.twig
  templates/security/reset_password/reset.html.twig
  templates/user_detail/commandHistory.html.twig
Labels: Reviewed

#362 Fix sécurité acces pdf
  src/Controller/PdfController.php
Labels: Reviewed

#363 Fix made in the view, so the command page in admin panel will open there is some command made by the admin (that has no userdetails data).
  templates/admin/command/index.html.twig
Labels: Reviewed

#364 ajout du prix dans le recap de la commande
  migrations/Version20210726074437.php
  src/Controller/ThanksController.php
  src/DataFixtures/CommandFixtures.php
  src/Entity/Command.php
  templates/admin/command/index.html.twig
Labels: Reviewed

#365 ajout adresse de livraison
  templates/admin/command/index.html.twig
Labels: Reviewed

#366 Fix_Generaux
  assets/images/waves.svg
  templates/admin/command/index.html.twig
  templates/admin/theme/_delete_form.html.twig
Labels: Reviewed

#369 fix placeholder contact
  src/Form/ContactType.php
Labels: Reviewed

#368 Fix - Responsivity, design and data update from command (price, delivery address)
  src/Controller/UserDetailController.php
  templates/user_detail/commandHistory.html.twig
Labels: Reviewed

#371 fix affichage des details utilisateur dans les commandes
  templates/admin/command/index.html.twig
Labels: Reviewed

#370 securisation et modification de la commande si la commande n'est pas …
  src/Controller/GameCreationController.php
  src/Controller/MemberController.php
  src/Controller/PreviewController.php
  src/Controller/ThanksController.php
  src/Entity/Status.php
  src/Service/GameCard.php
  templates/gameCreation/preview.html.twig
  templates/member/index.html.twig
Labels: Reviewed

#367 Dev ==> Master
  assets/images/waves.svg
  migrations/Version20210726074437.php
  src/Controller/GameCreationController.php
  src/Controller/MemberController.php
  src/Controller/PdfController.php
  src/Controller/PreviewController.php
  src/Controller/ThanksController.php
  src/Controller/UserDetailController.php
  src/DataFixtures/CommandFixtures.php
  src/Entity/Command.php
  src/Entity/Status.php
  src/Form/ContactType.php
  src/Service/GameCard.php
  templates/admin/command/index.html.twig
  templates/admin/theme/_delete_form.html.twig
  templates/gameCreation/preview.html.twig
  templates/member/index.html.twig
  templates/user_detail/commandHistory.html.twig
Labels: Reviewed

#372 j'espere que le tri va s'afficher
  templates/admin/command/index.html.twig
Labels: Reviewed

#373 fix variable en dur dans le contactController mailTo
  config/services.yaml
  src/Controller/ContactController.php
Labels: Reviewed

#374 fix exp
  templates/admin/user/index.html.twig
Labels: Reviewed

#375 Fixing double error at first page Game Creation
  templates/gameCreation/index.html.twig
Labels: Reviewed

#376 fix_enregistrement_du_nom_modifie_creation_jeu_etape1
  src/Controller/GameCreationController.php
Labels: Reviewed

#377 dev to master
  config/services.yaml
  src/Controller/ContactController.php
  src/Controller/GameCreationController.php
  templates/admin/command/index.html.twig
  templates/admin/user/index.html.twig
  templates/gameCreation/index.html.twig
Labels: Reviewed

#378 fix exp
  assets/images/waves.svg
  templates/admin/command/index.html.twig
Labels: Reviewed

#379 Dev => Master
  assets/images/waves.svg
  templates/admin/command/index.html.twig
Labels: Reviewed
